var webpack=require("webpack");
var path = require('path');
module.exports={
	entry:{
		banner:"./js/banner.js",
		gender:"./js/gender.js",
		illness:"./js/illness.js",
		basicInfo:"./js/basicInfo.js",
		howFeel:"./js/howFeel.js",
		allergy:"./js/allergy.js",
		status:"./js/status.js"
	},
	output:{
		path:"dist/",
		filename:"js/[name].js",
		publicPath:'../dist/'
	},
	module:{
		loaders:[{
			test:/\.css$/,
			loader:"style!css"
		},{
			test:/\.scss$/,loader:["style","css","scss"]
		},{
			test:/\.(png|jpg)$/,
			loader:"file-loader?limit=8192&name=img/[name].[ext]"
		}]
	}
}